# 注意: yaml语法的冒号后面要加个空格
# Note: A space is added after the colon of the yaml syntax.

# email 配置
email_host: smtp.qq.com
email_port: 465
email_username: your@qq.com
email_password: your_password
email_sender: your@qq.com
email_receiver: your@qq.com

title_filters: 
- '404'
- '403'
- '400'
- '502'
- '504'
- '500'
- Welcome to nginx!
- 旗舰店
- 专营店
- 专卖店
- 自营专区
- 馆
- 用品
- 首页-.*-淘宝网
- 店铺
- 不存在

html_filters: 
- was not found on this server
